// src/frontend/sample-react/App.tsx
import React from 'react';

const styles = {
    container: {
        height: '100%',
        padding: '2em',
        textAlign: 'center' as const,
        backgroundColor: 'lightgrey'
    },
    button: {
        padding: '0.5em'
    }
};

export default function App() {

    const [ count, setCount ] = React.useState(0);

    return (
        <div style={styles.container}>
            <h3>Hello React Button</h3>
            <button onClick={() => setCount(count + 1)} style={styles.button}>
                Clicked: {count}
            </button>
        </div>
    );
}

// src/frontend/sample-vue/App.vue
<script setup lang="ts">
    import { ref } from 'vue';

    const count = ref(0);
    const increment = () => {
        count.value++;
    };
</script>

<style scoped>
    #container {
        height: 100%;
        padding: 2em;
        text-align: center;
        background-color: lightgrey;
    }
    button{
        padding: 0.5em;
    }
</style>

<template>
    <div id="container">
        <h3>Hello Vue Button</h3>
        <button @click="increment">
            Clicked {{ count }} {{ count === 1 ? 'time' : 'times' }}
        </button>
    </div>
</template>
